### ISSUE TITLE
Create an Alire crate

### ISSUE THREAD

**Issue by JeremyGrosser** [AdaCore/Platinum_Reusable_Stack#5]
This library looks really nice, I'd love to be able to use it as an Alire crate. I think we could use [crate configuration options](https://alire.ada.dev/docs/#using-crate-configuration) to select between the different implementations.

**Comment by pat-rogers** [comment]
Indeed I intend to create a crate for it.

I had planned to rearrange it so that only the final, fully-proven "platinum" implementation is present.  Do you think the other impls would be useful?

**Comment by JeremyGrosser** [comment]
As long as the platinum implementation can run on a ZFP/Light runtime, I don't see any need for the others.

**Comment by pat-rogers** [comment]
Yes, no worries there.

**Comment by pat-rogers** [comment]
In fact I've decided to release that specific (stack) package along with some others that are either just now finished or are under development. I've got fully proved bounded queues and ring buffers, for example. These would be in a separate repo/crate from this one. More info when it is ready...
